### ISSUE TITLE
How could I find extrinsic hash 

### ISSUE THREAD

**Issue by turndealer** [kianenigma/polkadot-basic-notification#10]
Hi , 

I am trying to located Balance , Transfers , Where From/To and amount are found.

However extrinsic hash for the transfer can not be found .

could you help me figure it out ?

Thank you !

**Comment by turndealer** [comment]
I created solution for it .

I imported event data for the extrinsic hash , that made me to build hybird block data, which has extrinsic hash with event data, Like from , to , amount etc.

Thank you !

**Comment by kianenigma** [comment]
cheers!
